export type EventMeta = {
  id: string; // autogenerated
  name: string;
  timestamp: string;
  source?: string;
  payloadSummary?: string;
};

export type ChronosEvent<T = any> = {
  meta: EventMeta;
  payload: T;
};

export type Permission = {
  id: string;
  name: string;
  description?: string;
  grantedAt?: string;
  expiresAt?: string | null;
  incentiveTokens?: number; // how many incentive tokens granted when permission granted
  grantedBy?: string;
};

export type AuditRecord = {
  timestamp: string;
  action: string;
  data?: any;
  signature?: string;
};
